### PR TITLE
Added a StringExtensions method called DoesNotEqual. This will allow …

### PR DESCRIPTION
**Pull request by ghost**
…you to test inequality in strings with easy to read syntax.

### CODE REVIEW

**Comment by SneakyPeet** [comment]
I tend to agree to statement made in the slack channel to rather use == and != as the implementation is as below

```
public static bool operator == (String a, String b) {
    return String.Equals(a, b);
}
public static bool operator != (String a, String b) {
    return !String.Equals(a, b);
}
```

However I do not see the harm in this. @Sereph what do you think?

**Comment by ghost** [comment]
I did not realise that C# had overloaded the == and != operator. Coming from java I thought it was always better to use .Equals on string objects. That is why I had proposed this change :smile:

**Comment by SneakyPeet** [comment]
Going To Close This request then

**Comment by ghost** [comment]
Hehe, OK :smiley: I will think of something else to add :)

**Comment by SneakyPeet** [comment]
Dude +1 For Submitting a request! keep it up

**Comment by eXigentCoder** [comment]
Yeah lol, that issue totally got me when I was working on Java for a short period of time, C# is king of syntactical-sugar!

**Comment by ghost** [comment]
@Sereph I'm glad that I'm not the only one :D

**Pull request closed without merging**
